version: "3.9"

services:
  jenkins:
    image: jenkins/jenkins:lts-jdk17
    build:
      context: .
      dockerfile: Dockerfile.jenkins
    container_name: jenkins
    user: root               # ğŸ‘ˆ IMPORTANT
    ports:
      - "8085:8080"
      - "50000:50000"
    volumes:
      - jenkins_jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker   # ğŸ‘ˆ gives docker CLI
    restart: unless-stopped
    networks:
      - ims-network

networks:
  ims-network:
    external: true

volumes:
  jenkins_jenkins_home:
    external: true
